add Format-like printers
Chris00/ANSITerminal pull request #2
Opened 2017-12-01 16:25 UTC by vbmithr

Needed some support for `Format`. What do you think about it?

2017-12-03 13:47 UTC, Chris00 requested changes

2017-12-03 13:47 UTC, Chris00 commented on src/ANSITerminal.mli
> +
The above two lines are not part of your changes  — keep them as they were.

2017-12-03 13:47 UTC, Chris00 commented on src/ANSITerminal.mli
> +end
Please document this function.

2017-12-03 13:47 UTC, Chris00 commented on src/ANSITerminal.mli
> +module Format : sig
All the functions of this module and the module itself need to be documented.

2017-12-03 13:47 UTC, Chris00 commented on src/ANSITerminal_unix.ml
> +let print_with style txt oc =
I do not mind you modify earlier code as part of your PR but could you please split it in two commits: one for existing code modifications — including moving printf functions to their own sub-module — and one adding Format support.

2017-12-03 13:47 UTC, Chris00 commented on src/ANSITerminal_unix.ml
> +let ppf_print_with style txt ppf =
This function should be in the `Format` sub-module IMHO.

2017-12-03 13:47 UTC, Chris00 commented on src/ANSITerminal_win.ml
> +  let fprintf _ _ _ = invalid_arg "not implemented"
Need to be implemented.

2017-12-03 13:47 UTC, Chris00 commented on src/ANSITerminal_win.ml
> +module Format = struct
Functions of this module need to be implemented on Windows as well — make it a separated commit if you wish.

2017-12-04 15:36 UTC, vbmithr commented
Thanks for the comments. Closing for now, might re-open and work on it later.

2017-12-04 15:36 UTC, closed without merging